In [1]:
pip install pandas

Requirement already satisfied: pandas in .\venv\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in .\venv\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in .\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## Introduction to Panadas: Series and Data Frames

In [5]:
import pandas as pd

# Create a Pandas Series from a list
data = [10, 20, 30, 40]
series = pd.Series(data)

# Display the Series
series

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
# Create a Pandas Series with a custom index
series = pd.Series(data, index=['a','b','c','d'])
series

a    10
b    20
c    30
d    40
dtype: int64

In [7]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   City    3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [10]:
df.describe()

        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [11]:
df.dtypes

Name      str
Age     int64
City      str
dtype: object